// Fictional demonstration facilities. Never presented as verified or operational providers.
const rows = [
  [
    "lagos",
    "Lagos",
    "Nigeria",
    "NG",
    "Africa/Lagos",
    6.5244,
    3.3792,
    "₦",
    "NGN",
  ],
  [
    "accra",
    "Accra",
    "Ghana",
    "GH",
    "Africa/Accra",
    5.6037,
    -0.187,
    "GH₵",
    "GHS",
  ],
  [
    "nairobi",
    "Nairobi",
    "Kenya",
    "KE",
    "Africa/Nairobi",
    -1.2921,
    36.8219,
    "KSh",
    "KES",
  ],
  [
    "kigali",
    "Kigali",
    "Rwanda",
    "RW",
    "Africa/Kigali",
    -1.9441,
    30.0619,
    "RF",
    "RWF",
  ],
  [
    "cairo",
    "Cairo",
    "Egypt",
    "EG",
    "Africa/Cairo",
    30.0444,
    31.2357,
    "E£",
    "EGP",
  ],
  [
    "casablanca",
    "Casablanca",
    "Morocco",
    "MA",
    "Africa/Casablanca",
    33.5731,
    -7.5898,
    "MAD",
    "MAD",
  ],
  [
    "cape-town",
    "Cape Town",
    "South Africa",
    "ZA",
    "Africa/Johannesburg",
    -33.9249,
    18.4241,
    "R",
    "ZAR",
  ],
  [
    "dakar",
    "Dakar",
    "Senegal",
    "SN",
    "Africa/Dakar",
    14.7167,
    -17.4677,
    "CFA",
    "XOF",
  ],
];
export const locations = rows.map(
  ([id, city, country, code, timeZone, lat, lng, symbol, currency]) => ({
    id,
    city,
    country,
    code,
    timeZone,
    lat,
    lng,
    symbol,
    currency,
  }),
);
export const countries = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic",
  "Chad",
  "Comoros",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Côte d’Ivoire",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger",
  "Nigeria",
  "Rwanda",
  "São Tomé and Príncipe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan",
  "Tanzania",
  "Togo",
  "Tunisia",
  "Uganda",
  "Zambia",
  "Zimbabwe",
];
export function demoData() {
  const facilities = locations.flatMap((l, i) => [
    {
      _id: `${l.id}-care`,
      name: `AERIX ${l.city} Care Centre`,
      kind: "hospital",
      city: l.city,
      country: l.country,
      locationId: l.id,
      timeZone: l.timeZone,
      lat: l.lat,
      lng: l.lng,
      services: ["General care", "Family medicine", "Health screening", "Dentistry", "Surgery", "Paediatrics"],
      accepting: true,
      hours: "Mon–Sat · 08:00–18:00",
      description:
        "A welcoming sample clinic for everyday care, preventive check-ups and family health.",
      address: `Illustrative ${l.city} location`,
      sample: true,
      updatedAt: new Date().toISOString(),
      color: "violet",
      image: "care",
    },
    {
      _id: `${l.id}-family`,
      name: `Bloom Family Clinic · ${l.city}`,
      kind: "hospital",
      city: l.city,
      country: l.country,
      locationId: l.id,
      timeZone: l.timeZone,
      lat: l.lat + 0.024,
      lng: l.lng + 0.02,
      services: ["General care", "Paediatrics", "Women’s health", "Dentistry", "Surgery"],
      accepting: i % 3 !== 1,
      hours: "Mon–Fri · 09:00–17:00",
      description:
        "A fictional community clinic focused on care at every stage of life.",
      address: `Illustrative ${l.city} location`,
      sample: true,
      updatedAt: new Date().toISOString(),
      color: "peach",
      image: "family",
    },
    {
      _id: `${l.id}-pharmacy`,
      name: `Leaf Pharmacy · ${l.city}`,
      kind: "pharmacy",
      city: l.city,
      country: l.country,
      locationId: l.id,
      timeZone: l.timeZone,
      lat: l.lat - 0.015,
      lng: l.lng + 0.012,
      services: ["Pharmacy collection", "Pharmacist consultation"],
      accepting: true,
      hours: "Mon–Sat · 09:00–19:00",
      description:
        "A sample pharmacy showing product availability and collection requests.",
      address: `Illustrative ${l.city} location`,
      sample: true,
      updatedAt: new Date().toISOString(),
      color: "green",
      image: "pharmacy",
    },
  ]);
  const products = locations.flatMap((l) => [
    {
      _id: `${l.id}-first-aid`,
      pharmacyId: `${l.id}-pharmacy`,
      name: "Everyday first-aid kit",
      category: "First aid",
      description: "A compact kit for your home essentials.",
      price: l.code === "NG" ? 8500 : 25,
      currency: l.currency,
      stock: 12,
      prescription: false,
      icon: "kit",
    },
    {
      _id: `${l.id}-thermometer`,
      pharmacyId: `${l.id}-pharmacy`,
      name: "Digital thermometer",
      category: "Devices",
      description: "An easy-to-read addition to your care kit.",
      price: l.code === "NG" ? 4500 : 15,
      currency: l.currency,
      stock: 8,
      prescription: false,
      icon: "thermometer",
    },
    {
      _id: `${l.id}-dressings`,
      pharmacyId: `${l.id}-pharmacy`,
      name: "Sterile dressing pack",
      category: "First aid",
      description: "Individually wrapped wound dressings.",
      price: l.code === "NG" ? 2200 : 8,
      currency: l.currency,
      stock: 20,
      prescription: false,
      icon: "bandage",
    },
    {
      _id: `${l.id}-prescription`,
      pharmacyId: `${l.id}-pharmacy`,
      name: "Prescription medicine enquiry",
      category: "Prescription",
      description:
        "Speak to a licensed pharmacist with a valid prescription. Online ordering is not enabled.",
      price: 0,
      currency: l.currency,
      stock: 0,
      prescription: true,
      icon: "pill",
    },
  ]);
  const users = [
    {
      _id: "demo-patient",
      name: "Alex Morgan",
      email: "patient@demo.aerix.invalid",
      role: "patient",
    },
    {
      _id: "demo-clinic",
      name: "Clinic team",
      email: "clinic@demo.aerix.invalid",
      role: "clinic",
      facilityId: "lagos-care",
    },
    {
      _id: "demo-pharmacy",
      name: "Pharmacy team",
      email: "pharmacy@demo.aerix.invalid",
      role: "pharmacy",
      facilityId: "lagos-pharmacy",
    },
    {
      _id: "demo-admin",
      name: "AERIX administrator",
      email: "admin@demo.aerix.invalid",
      role: "admin",
    },
  ];
  const doctors = facilities
    .filter((facility) => facility.kind === "hospital")
    .flatMap((facility) => [
      ["general", "AERIX Demo General Practitioner", "General practitioner"],
      ["dentist", "AERIX Demo Dentist", "Dentistry"],
      ["surgeon", "AERIX Demo Surgeon", "Surgery"],
      ["paediatrician", "AERIX Demo Paediatrician", "Paediatrics"],
    ].map(([key, name, specialty]) => ({
      _id: `${facility._id}-demo-${key}`,
      facilityId: facility._id,
      name,
      specialty,
      active: true,
      sample: true,
    })));
  return {
    facilities,
    products,
    users,
    doctors,
    availability: [],
    appointments: [],
    orders: [],
    sessions: [],
    applications: [],
    audit: [],
  };
}
